-- database.sql`database`
CREATE DATABASE IF NOT EXISTS snake_adopt CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE snake_adopt;

-- tabel users/adopters
CREATE TABLE adopters (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,applications
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- tabel snakes =
CREATE TABLE snakes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  species VARCHAR(50) NOT NULL,
  age VARCHAR(50),
  gender ENUM('Male','Female','Unknown') DEFAULT 'Unknown',
  description TEXT,
  photo VARCHAR(255), -- path ke file
  status ENUM('Available','Adopted') DEFAULT 'Available',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- tabel aplikasi adopsi
CREATE TABLE applications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  snake_id INT NOT NULL,
  adopter_id INT NOT NULL,
  message TEXT,
  status ENUM('Pending','Approved','Rejected') DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (snake_id) REFERENCES snakes(id) ON DELETE CASCADE,
  FOREIGN KEY (adopter_id) REFERENCES adopters(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- tabel admin sederhana (bisa diperluas later)
CREATE TABLE admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL -- store hashed password
) ENGINE=InnoDB;

-- contoh data

INSERT INTO snakes (name, species, age, gender, description, photo, status, created_at) VALUES
('Serpentis', 'Boa Constrictor', 5, 'Male', 'Ular yang kuat, terkenal dengan kekuatannya dalam memeluk mangsa.', 'link_foto', 'Available', '2025-10-15'),
('Nebula', 'Ball Python', 3, 'Female', 'Ular dengan pola yang mempesona, seperti langit malam penuh bintang.', 'link_foto', 'Available', '2025-10-15'),
('Vortex', 'King Cobra', 7, 'Male', 'Ular berbisa terpanjang, ditakuti karena serangannya yang mematikan.', 'link_foto', 'Available', '2025-10-15'),
('Eclipse', 'Reticulated Python', 8, 'Female', 'Dikenal dengan pola indah dan ukuran tubuhnya yang sangat besar.', 'link_foto', 'Available', '2025-10-15'),
('Shadow', 'Black Mamba', 4, 'Male', 'Ular berbisa yang sangat cepat, dengan gerakan mematikan.', 'link_foto', 'Available', '2025-10-15'),
('Titan', 'Green Anaconda', 6, 'Female', 'Ular terbesar dan terberat di dunia, sangat kuat.', 'link_foto', 'Available', '2025-10-15'),
('Onyx', 'Gaboon Viper', 2, 'Male', 'Ular dengan penampilan yang sangat tersembunyi, mematikan saat menyerang.', 'link_foto', 'Available', '2025-10-15'),
('Venom', 'Copperhead', 3, 'Female', 'Ular berbisa dengan kepala berwarna tembaga dan tanda khas di tubuhnya.', 'link_foto', 'Available', '2025-10-15'),
('Phantom', 'Timber Rattlesnake', 9, 'Male', 'Ular dengan suara derit khas yang memberi peringatan sebelum menyerang.', 'link_foto', 'Available', '2025-10-15');



INSERT INTO adopters (name, email, phone) VALUES
('Budi', 'budi@example.com', '081234567890'),
('Siti', 'siti@example.com', '082345678901');

-- admin default: username admin, password: admin123 (hashed)
-- hash admin123 with password_hash in PHP: example below uses bcrypt
INSERT INTO admins (username, password) VALUES
('admin123', 'admin123');
-- Note: hash corresponds to 'admin123' generated by password_hash('admin123', PASSWORD_DEFAULT)


UPDATE admins
SET password = '$2y$10$DH0MgP/aqIUXeeT8TuwO5OKaofPdN9zrbp0FmqzpLOmGt0nl64VRS'
WHERE username = 'admin';

ALTER TABLE applications
ADD COLUMN snake_id INT NOT NULL AFTER id;

snakesDROP TABLE IF EXISTS applications;
CREATE TABLE applications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  snake_id INT NOT NULL,
  adopter_id INT NOT NULL,
  message TEXT,
  status ENUM('Pending','Approved','Rejected') DEFAULT 'Pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (snake_id) REFERENCES snakes(id) ON DELETE CASCADE,
  FOREIGN KEY (adopter_id) REFERENCES adopters(id) ON DELETE CASCADE
);

select * FROM admins;
select * FROM snakes;
select * FROM adopters;
select * FROM applications;